---
title: "week_3_exercise"
author: "Tim Fässler"
date: "5/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preparation

```{r}
library(readr)
library(sf)
library(dplyr)
library(ggplot2)
library(gridExtra)

```

# Task 1: Segmentation
```{r}
data <- read_delim("caro60.csv", ",")
caro <- data.frame(data)
  

caro <- caro %>%
  mutate(
    nMinus3 = sqrt((lag(E,3)-E)^2+(lag(N,3)-N)^2),
    nMinus2 = sqrt((lag(E,2)-E)^2+(lag(N,2)-N)^2),
    nMinus1 = sqrt((lag(E,1)-E)^2+(lag(N,1)-N)^2),
    nPlus1  = sqrt((E-lead(E,1))^2+(N-lead(N,1))^2), 
    nPlus2  = sqrt((E-lead(E,2))^2+(N-lead(N,2))^2),
    nPlus3  = sqrt((E-lead(E,3))^2+(N-lead(N,3))^2)
  )

caro <- caro %>%
  rowwise() %>%
  mutate(
    stepMean = mean(c(nMinus3, nMinus2, nMinus1,nPlus1,nPlus2, nPlus3))
  ) %>%
  ungroup()

summary(caro$stepMean)
```

# Task 2: Specify and apply threshold d

```{r}
hist(caro$stepMean)

caro <- caro %>% 
  ungroup() %>%
  mutate(static = stepMean < 10)
```

# Task 3: Visualize segmented trajectories

```{r}

caro_filter <- caro %>%
  filter(!static)

caro_filter%>%
  ggplot(aes(E, N))  +
  geom_path() +
  geom_point() +
  coord_fixed() +
  theme(legend.position = "bottom") +
  ggtitle("Only points while moving")


ggplot() +
  geom_path(caro_filter, mapping = aes(E, N)) +
  geom_point(caro, mapping = aes(E, N, color = static)) +
  ggtitle("Static vs moving points")
```
# Task 4: Segment-based analysis

```{r}
rle_id <- function(vec){
  x <- rle(vec)$lengths
  as.factor(rep(seq_along(x), times=x))
}

caro <- caro %>% mutate(segment_id = rle_id(static))

seg_colors <- filter(caro, static == FALSE)
seg_long <- seg_colors %>% group_by(segment_id) %>% mutate(long = length(segment_id)) %>% filter(long >= 5)

ggplot() +
  geom_path(seg_colors, mapping = aes(E, N, color = seg_colors$segment_id)) +
  geom_point(seg_colors, mapping = aes(E, N, color = seg_colors$segment_id)) +
  scale_color_discrete("Segment Number") +
  ggtitle("All Segments")

ggplot() +
  geom_path(seg_long, mapping = aes(E, N, color = seg_long$segment_id)) +
  geom_point(seg_long, mapping = aes(E, N, color = seg_long$segment_id)) +
  scale_color_discrete("Segment Number") +
  ggtitle("All Segments with >= 5 Nodes")


```

# Task 5

```{r}

pedestrian <- read_delim("pedestrian.csv", ",") %>% data.frame()

tra1 <- ggplot() +
  geom_point(pedestrian, mapping = aes(E, N), alpha = 0.1) +
  geom_point(subset(pedestrian, TrajID %in% "1"), mapping = aes(E, N), color = "red") +
  geom_path(subset(pedestrian, TrajID %in% "1"), mapping = aes(E, N), color = "red") +
  ggtitle("TrajID: 1")

tra2 <- ggplot() +
  geom_point(pedestrian, mapping = aes(E, N), alpha = 0.1) +
  geom_point(subset(pedestrian, TrajID %in% "2"), mapping = aes(E, N), color = "yellow") +
  geom_path(subset(pedestrian, TrajID %in% "2"), mapping = aes(E, N), color = "yellow") +
  ggtitle("TrajID: 2")

tra3 <- ggplot() +
  geom_point(pedestrian, mapping = aes(E, N), alpha = 0.1) +
  geom_point(subset(pedestrian, TrajID %in% "3"), mapping = aes(E, N), color = "green") +
  geom_path(subset(pedestrian, TrajID %in% "3"), mapping = aes(E, N), color = "green") +
  ggtitle("TrajID: 3")

tra4 <- ggplot() +
  geom_point(pedestrian, mapping = aes(E, N), alpha = 0.1) +
  geom_point(subset(pedestrian, TrajID %in% "4"), mapping = aes(E, N), color = "darkgreen") +
  geom_path(subset(pedestrian, TrajID %in% "4"), mapping = aes(E, N), color = "darkgreen") +
  ggtitle("TrajID: 4")

tra5 <- ggplot() +
  geom_point(pedestrian, mapping = aes(E, N), alpha = 0.1) +
  geom_point(subset(pedestrian, TrajID %in% "5"), mapping = aes(E, N), color = "blue") +
  geom_path(subset(pedestrian, TrajID %in% "5"), mapping = aes(E, N), color = "blue") +
  ggtitle("TrajID: 5")

tra6 <- ggplot() +
  geom_point(pedestrian, mapping = aes(E, N), alpha = 0.1) +
  geom_point(subset(pedestrian, TrajID %in% "6"), mapping = aes(E, N), color = "pink") +
  geom_path(subset(pedestrian, TrajID %in% "6"), mapping = aes(E, N), color = "pink") +
  ggtitle("TrajID: 6")

grid.arrange(tra1, tra2, tra3, tra4, tra5, tra6, nrow = 2, top = "Visual Comparisons of the 6 trajectories")

```

